### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by UhFinOnDiscord** [CGray1234/Roblox-Webhook-System#4]
When a TextButton on a SurfaceGUI is clicked it sends a webhook stating which user clicked the button

**Comment by CGray1234** [comment]
The script I made works on a ScreenGui, but not a SurfaceGui. Here's the steps if you can manage to find a fix for this:

Step 1. Make a RemoteEvent and place it in ReplicatedStorage
Step 2. In your TextButton, make a LocalScript and but the following code in it:

```
script.Parent.MouseButton1Click:Connect(function()
	
	local player = game:GetService("Players").LocalPlayer.Name
	
	game:GetService("ReplicatedStorage").RemoteEvent:FireServer(player)
end)
```

Step 3. In ServerScriptService, make a script and put the following code into it:

```local webhookURL = "https://hooks.hyra.io/api/webhooks/numbers/symbols" --Replace with the webhook URL. DO NOT CHANGE hooks.hyra.io!!! DOING SO WILL BREAK IT! More info here: https://devforum.roblox.com/t/discord-webhook-proxy/1500688
local HttpService = game:GetService("HttpService")

game:GetService("ReplicatedStorage").RemoteEvent.OnServerEvent:Connect(function(player)
	--Add whatever you want right here, if you would like me to make a script designed so that when a player chats a command or anything, please create an issue in the issues tab
	local data = {
		["content"] = player.Name.." pushed a button!" --Unlike embeds, ["content"] is a normal-looking message
	}

	local encodedData = HttpService:JSONEncode(data)
	HttpService:PostAsync(webhookURL, encodedData)
end)
```

Alternatively, you can change the content to an embed by using the "embeds.lua" script.

If you were able to find a fix for the surfacegui issue, please reply with the fix for future references. Thanks!
